apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: null
  generation: 1
  labels:
    app: rq2
  name: rq2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rq2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rq2
        clients: access
    spec:
      containers:
      - name: rqlite
        command: ['rqlited']
        args: ['-http-addr', ':4001', '-raft-addr', ':4002', '-http-adv-addr', 'rq2:4001', '-raft-adv-addr', 'rq2:4002', '-join', 'http://rq1:4001', '/rqlite/file/data']
        image: rqlite/rqlite
        imagePullPolicy: Always
        ports:
        - containerPort: 4001
        - containerPort: 4002
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /rqlite
          name: node-volume
        - mountPath: /node-id
          name: node-id
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: node-volume
      - emptyDir: {}
        name: node-id
status: {}
