apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    app: rq3
    clients: access
  name: rq3
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rq3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rq3
        clients: access
    spec:
      containers:
      - name: rqlite
        command:
        - bash
        - "-c"
        - |
          set -ex
          /bin/rqlited -http-addr ${HOSTNAME}:4001 -raft-addr ${HOSTNAME}:4002 -join http://rq1:4001 -http-adv-addr rq3:4001 -raft-adv-addr rq3:4002 /rqlite/file/data
        # readinessProbe:
        #   tcpSocket:
        #     port: 4001
        #     initialDelaySeconds: 5
        #     periodSeconds: 10
          # livenessProbe:
          #   tcpSocket:
          #     port: 4001
          #   initialDelaySeconds: 20
          #   periodSeconds: 20
        image: rqlite/rqlite:5.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 4001
        - containerPort: 4002
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /rqlite
          name: node-volume
        - mountPath: /node-id
          name: node-id
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: node-volume
      - emptyDir: {}
        name: node-id
status: {}
